-- Precomputed report tables (operator's pattern): create the STRUCTURE now, link
-- each report to it, so the report returns 200 (empty) today and auto-populates
-- the moment its data pipeline fills the table — NO code change needed.
-- Every table is vehicle/driver keyed + an event_time for the date-range filter,
-- matching the ReportController contract (:from/:to, :vehicleIds, :driverIds).

CREATE TABLE IF NOT EXISTS telematics.rpt_door (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vehicle_id integer NOT NULL, driver_id integer,
    event_time timestamptz NOT NULL,
    type text, open_sec integer, close_sec integer,
    open_to_close_sec integer, current_door_status text, location text);

CREATE TABLE IF NOT EXISTS telematics.rpt_seatbelt (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vehicle_id integer NOT NULL, driver_id integer,
    event_time timestamptz NOT NULL,
    type text, duration_sec integer, speed_kmh numeric, location text);

CREATE TABLE IF NOT EXISTS telematics.rpt_immobilizer (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vehicle_id integer NOT NULL, driver_id integer,
    event_time timestamptz NOT NULL,
    action text, location text);

CREATE TABLE IF NOT EXISTS telematics.rpt_rfid (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vehicle_id integer NOT NULL, driver_id integer,
    event_time timestamptz NOT NULL,
    rfid_tag text, action text, event_location text, playback_url text);

CREATE TABLE IF NOT EXISTS telematics.rpt_fuel_event (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vehicle_id integer NOT NULL, driver_id integer,
    event_time timestamptz NOT NULL,
    event_type text, amount_l numeric, fuel_level_before numeric,
    fuel_level_after numeric, odometer_km numeric, fuel_cost numeric, location text);

CREATE TABLE IF NOT EXISTS telematics.rpt_temp_humidity (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vehicle_id integer NOT NULL, driver_id integer,
    event_time timestamptz NOT NULL,
    sensor_name text, temperature_c numeric, humidity_pct numeric, location text);

CREATE TABLE IF NOT EXISTS telematics.rpt_sensor_analog (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vehicle_id integer NOT NULL, driver_id integer,
    event_time timestamptz NOT NULL,
    channel text, value numeric, unit text, location text);

DO $$
DECLARE t text;
BEGIN
  FOREACH t IN ARRAY ARRAY['rpt_door','rpt_seatbelt','rpt_immobilizer','rpt_rfid',
                           'rpt_fuel_event','rpt_temp_humidity','rpt_sensor_analog']
  LOOP
    EXECUTE format('CREATE INDEX IF NOT EXISTS %I ON telematics.%I (vehicle_id, event_time DESC)', t||'_veh_time_idx', t);
    EXECUTE format('GRANT SELECT ON telematics.%I TO telematics', t);
  END LOOP;
END $$;
