-- Batch-3 precompute tables — cover the last 29 reports (structure now, fill later).
CREATE TABLE IF NOT EXISTS telematics.rpt_geofence_event (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vehicle_id integer NOT NULL, driver_id integer, event_time timestamptz NOT NULL,
    geofence_id integer, geofence_name text, event_type text, duration_sec integer, location text);

CREATE TABLE IF NOT EXISTS telematics.rpt_geofence_assignment (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vehicle_id integer, geofence_id integer, geofence_name text, vehicle_name text, imei text);

CREATE TABLE IF NOT EXISTS telematics.rpt_driver_score (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    driver_id integer, driver_name text, contact_number text, period_start date, period_end date,
    safety_score numeric, total_score numeric, rag_band text, harsh_accel integer, harsh_brake integer,
    harsh_corner integer, overspeed_count integer, seatbelt_count integer,
    distance_km numeric, driving_hours numeric, rides_count integer);

CREATE TABLE IF NOT EXISTS telematics.rpt_driver_workload (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    driver_id integer, driver_name text, date date, login_time timestamptz, logout_time timestamptz,
    working_sec integer, driving_sec integer, idle_sec integer, distance_km numeric);

CREATE TABLE IF NOT EXISTS telematics.rpt_driver_rfid (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vehicle_id integer NOT NULL, driver_id integer, event_time timestamptz NOT NULL,
    rfid_tag text, driver_name text, action text, location text);

CREATE TABLE IF NOT EXISTS telematics.rpt_document (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subject_type text, driver_id integer, vehicle_id integer, company_name text, branch_name text,
    employee_number text, driver_name text, object_label text, document_type text, document_name text,
    issue_date date, expiry_date date, status text, notes text);

CREATE TABLE IF NOT EXISTS telematics.rpt_maintenance (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vehicle_id integer, object_label text, company_name text, branch_name text, reminder_type text,
    schedule text, description text, issue_date date, expiry_date date, frequency text, every_x numeric,
    due_distance_km numeric, due_engine_hours numeric, status text, prev_ack_date date);

CREATE TABLE IF NOT EXISTS telematics.rpt_wasl_status (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subject_type text, company_id integer, driver_id integer, vehicle_id integer,
    ref_key text, name text, wasl_status text, registered_at timestamptz, last_sync timestamptz, message text);

CREATE TABLE IF NOT EXISTS telematics.rpt_admin_log (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    log_time timestamptz, actor text, action text, entity_type text, entity_name text,
    details text, ip text, status text);

DO $$
DECLARE t text;
BEGIN
  FOREACH t IN ARRAY ARRAY['rpt_geofence_event','rpt_geofence_assignment','rpt_driver_score',
      'rpt_driver_workload','rpt_driver_rfid','rpt_document','rpt_maintenance','rpt_wasl_status','rpt_admin_log']
  LOOP EXECUTE format('GRANT SELECT ON telematics.%I TO telematics', t); END LOOP;
END $$;
