-- Batch-2 precompute report tables (structure now, auto-fill later).
CREATE TABLE IF NOT EXISTS telematics.rpt_load_event (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vehicle_id integer NOT NULL, driver_id integer, event_time timestamptz NOT NULL,
    event_type text, load_status text, weight_kg numeric, location text);

CREATE TABLE IF NOT EXISTS telematics.rpt_weight (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vehicle_id integer NOT NULL, driver_id integer, event_time timestamptz NOT NULL,
    axle text, weight_kg numeric, total_weight_kg numeric, overload_kg numeric, location text);

CREATE TABLE IF NOT EXISTS telematics.rpt_obd (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vehicle_id integer NOT NULL, driver_id integer, event_time timestamptz NOT NULL,
    pid text, pid_name text, value numeric, unit text);

CREATE TABLE IF NOT EXISTS telematics.rpt_digital (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vehicle_id integer NOT NULL, driver_id integer, event_time timestamptz NOT NULL,
    channel text, state text, location text);

CREATE TABLE IF NOT EXISTS telematics.rpt_video_alarm (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vehicle_id integer NOT NULL, driver_id integer, event_time timestamptz NOT NULL,
    alarm_type text, channel text, clip_url text, location text);

CREATE TABLE IF NOT EXISTS telematics.rpt_canbus (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vehicle_id integer NOT NULL, driver_id integer, event_time timestamptz NOT NULL,
    param text, value numeric, unit text, fuel_level numeric, rpm numeric,
    coolant_temp numeric, engine_load numeric);

CREATE TABLE IF NOT EXISTS telematics.rpt_passenger (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vehicle_id integer NOT NULL, driver_id integer, event_time timestamptz NOT NULL,
    boarded integer, alighted integer, occupancy integer, location text);

CREATE TABLE IF NOT EXISTS telematics.rpt_address_visit (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vehicle_id integer NOT NULL, driver_id integer, event_time timestamptz NOT NULL,
    address text, lat double precision, lng double precision,
    arrival_time timestamptz, departure_time timestamptz, duration_sec integer);

CREATE TABLE IF NOT EXISTS telematics.rpt_temp_reading (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vehicle_id integer NOT NULL, driver_id integer, event_time timestamptz NOT NULL,
    sensor_name text, temperature_c numeric, humidity_pct numeric,
    min_c numeric, max_c numeric, avg_c numeric, location text);

CREATE TABLE IF NOT EXISTS telematics.rpt_driver_fuel (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vehicle_id integer NOT NULL, driver_id integer, event_time timestamptz NOT NULL,
    distance_km numeric, fuel_used_l numeric, consumption_l_100km numeric, fuel_cost numeric);

DO $$
DECLARE t text;
BEGIN
  FOREACH t IN ARRAY ARRAY['rpt_load_event','rpt_weight','rpt_obd','rpt_digital',
      'rpt_video_alarm','rpt_canbus','rpt_passenger','rpt_address_visit',
      'rpt_temp_reading','rpt_driver_fuel']
  LOOP
    EXECUTE format('CREATE INDEX IF NOT EXISTS %I ON telematics.%I (vehicle_id, event_time DESC)', t||'_veh_time_idx', t);
    EXECUTE format('GRANT SELECT ON telematics.%I TO telematics', t);
  END LOOP;
END $$;
