-- ============================================================================
-- TELEMATICS SCHEMA — DDL DRAFT v1 (2026-07-18)
-- Fleet app backend schema living INSIDE the traccar database, isolated in
-- schema "telematics". App-owned data = real tables. Anything derivable from
-- Traccar's live tables (tc_positions / tc_events / tc_devices /
-- device_daily_stats) = views + functions, so there is ONE source of truth
-- and no second ingest pipeline.
--
-- Design rules
--  * The bridge to Traccar is telematics.vehicles.imei = tc_devices.uniqueid;
--    tc_device_id is cached for fast joins. NO hard FK into tc_* tables:
--    Traccar's own migrations/registerUnknown must stay free to manage them.
--  * App tables use timestamptz (app speaks ISO-8601 UTC). Traccar columns
--    are timestamp WITHOUT tz (UTC by convention) — the views cast at the edge.
--  * ids: GENERATED BY DEFAULT AS IDENTITY (bigint for high-volume tables).
--  * JSON-shaped payloads (permissions, polygon coords, sensor maps) = jsonb.
--  * Everything owned by role "telematics": full rights here, SELECT-only on
--    the Traccar tables it reads. Never write tc_* from the app.
-- ============================================================================

BEGIN;

CREATE SCHEMA IF NOT EXISTS telematics;

-- ---------------------------------------------------------------------------
-- Role & grants (run as superuser; password set at deploy time, not in file)
-- ---------------------------------------------------------------------------
DO $$ BEGIN
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'telematics') THEN
    CREATE ROLE telematics LOGIN;
  END IF;
END $$;

GRANT USAGE  ON SCHEMA telematics TO telematics;
ALTER DEFAULT PRIVILEGES IN SCHEMA telematics
  GRANT ALL ON TABLES    TO telematics;
ALTER DEFAULT PRIVILEGES IN SCHEMA telematics
  GRANT ALL ON SEQUENCES TO telematics;
-- read-only reach into Traccar data:
GRANT SELECT ON tc_devices, tc_positions, tc_events, device_daily_stats TO telematics;

SET LOCAL search_path = telematics, public;

-- ===========================================================================
-- 1. TENANCY / SECURITY
-- ===========================================================================
CREATE TABLE companies (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        text NOT NULL,
    created_at  timestamptz NOT NULL DEFAULT now(),
    deleted_at  timestamptz
);

CREATE TABLE branches (
    id             integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id     integer NOT NULL REFERENCES companies(id),
    branch_code    text,
    branch_name    text NOT NULL,
    contact_person text,
    mobile         text,
    email          text,
    city_state     text,
    country        text,
    created_at     timestamptz NOT NULL DEFAULT now(),
    deleted_at     timestamptz
);

CREATE TABLE accounts (
    id                       integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_account_id        integer REFERENCES accounts(id),
    account_type             text NOT NULL,             -- reseller | company | ...
    name                     text NOT NULL,
    username                 text UNIQUE,
    email                    text,
    recovery_email           text,
    status                   text NOT NULL DEFAULT 'active',
    default_language         text  DEFAULT 'en',
    default_time_zone        text  DEFAULT 'Asia/Riyadh',
    default_map_provider     text,
    default_distance_unit    text  DEFAULT 'km',
    default_speed_unit       text  DEFAULT 'kmh',
    default_trip_calc_mode   text,
    idle_threshold_seconds   integer DEFAULT 300,
    stop_threshold_seconds   integer DEFAULT 300,
    inactive_threshold_hours integer DEFAULT 24,
    created_at               timestamptz NOT NULL DEFAULT now(),
    modified_at              timestamptz,
    modified_by_account_id   integer,
    deleted_at               timestamptz
);

CREATE TABLE roles (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id  integer REFERENCES accounts(id),
    name        text NOT NULL,
    is_template boolean NOT NULL DEFAULT false,
    permissions jsonb NOT NULL DEFAULT '[]',            -- permission-key array
    created_at  timestamptz NOT NULL DEFAULT now(),
    deleted_at  timestamptz
);

CREATE TABLE users (
    id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id    integer NOT NULL REFERENCES accounts(id),
    tenant_id     integer,                              -- company scope
    username      text NOT NULL UNIQUE,
    password_hash text NOT NULL,                        -- bcrypt/argon2 — never plain
    role          text,                                 -- mock-style role string (superAdmin|admin|...)
    role_id       integer REFERENCES roles(id)
);

CREATE TABLE audit_log (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    integer,
    account_id integer,
    action     text NOT NULL,
    entity     text,
    entity_id  bigint,
    details    jsonb,
    at         timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX ON audit_log (at DESC);
CREATE INDEX ON audit_log (user_id, at DESC);

-- ===========================================================================
-- 2. FLEET REGISTRY  (the Traccar bridge lives here)
-- ===========================================================================
CREATE TABLE vehicle_groups (
    id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id integer REFERENCES companies(id),
    name       text NOT NULL
);

CREATE TABLE drivers (
    id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id      integer REFERENCES companies(id),
    driver_name     text NOT NULL,
    employee_number text,
    id_number       text,
    contact_number  text,
    rfid            text,
    active          boolean NOT NULL DEFAULT true
);

CREATE TABLE vehicles (
    id                integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id        integer NOT NULL REFERENCES companies(id),
    branch_id         integer REFERENCES branches(id),
    vehicle_group_id  integer REFERENCES vehicle_groups(id),
    driver_id         integer REFERENCES drivers(id),
    -- ── Traccar bridge ────────────────────────────────────────────────────
    imei              text NOT NULL UNIQUE,   -- = tc_devices.uniqueid
    tc_device_id      integer,                -- cached tc_devices.id (no FK, see header)
    -- ── registry (static truth owned by the app) ─────────────────────────
    vehicle_name      text NOT NULL,
    plate_number      text,
    vin               text,
    vehicle_brand     text,
    vehicle_model     text,
    icon_name         text,
    door_number       text,
    trailer_number    text,
    vehicle_mode      text NOT NULL DEFAULT 'operation',  -- operation|maintenance|...
    active            boolean NOT NULL DEFAULT true,
    fuel_tank_capacity_l numeric,
    tank_count        integer,
    -- device install metadata (from mock "devices" + vehicle device fields)
    device_type       text,
    device_brand      text,
    device_model      text,
    device_install_date date,
    device_warranty_until date,
    sim_number        text,
    sim_provider      text,
    time_zone         text,
    initial_odometer_km    numeric,
    initial_engine_hours   numeric,
    odometer_source   text,   -- gps | can
    speed_source      text,
    distance_source   text,
    working_hours_source text,
    distance_unit     text DEFAULT 'km',
    sensor_attributes jsonb,  -- static per-vehicle sensor config/calibration
    created_at        timestamptz NOT NULL DEFAULT now(),
    modified_at       timestamptz,
    modified_by_account_id integer,
    deleted_at        timestamptz
);
CREATE INDEX ON vehicles (company_id) WHERE deleted_at IS NULL;
CREATE INDEX ON vehicles (tc_device_id);
-- NOTE: lat/lng/speed/status/fuel/CAN/door/... deliberately NOT columns here.
-- Live state comes from v_live_vehicles below. Single source of truth.

-- ===========================================================================
-- 3. GEO
-- ===========================================================================
CREATE TABLE geofence_groups (
    id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id integer REFERENCES companies(id),
    name       text NOT NULL
);

CREATE TABLE geofences (
    id                 integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id         integer REFERENCES companies(id),
    geofence_group_id  integer REFERENCES geofence_groups(id),
    user_id            integer REFERENCES users(id),
    name               text NOT NULL,
    description        text,
    type               text NOT NULL,                 -- polygon | circle | corridor
    coordinates        jsonb NOT NULL,                -- GeoJSON-style coords
    color              text,
    address            text,
    fence_category     text,
    geofence_access    text,
    tags               text[],
    tolerance          numeric,
    area_sq_km         numeric,
    perimeter_km       numeric,
    active             boolean NOT NULL DEFAULT true,
    assigned_vehicle_ids integer[] DEFAULT '{}',
    assigned_group_ids   integer[] DEFAULT '{}',
    created_at         timestamptz NOT NULL DEFAULT now(),
    created_by_user_id integer,
    modified_at        timestamptz,
    modified_by_user_id integer
);
-- Later: consider PostGIS + geometry column and ST_Contains for server-side
-- geofence evaluation; jsonb coords are enough while evaluation stays in app.

CREATE TABLE address_groups (
    id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id integer REFERENCES companies(id),
    name       text NOT NULL
);

CREATE TABLE addresses (
    id               integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id       integer REFERENCES companies(id),
    address_group_id integer REFERENCES address_groups(id),
    name             text NOT NULL,
    lat              double precision,
    lng              double precision,
    radius_m         numeric,
    details          jsonb
);

-- ===========================================================================
-- 4. MOVEMENT HISTORY OWNED BY APP
--    (trips are classified/editable by the app => table, seeded from Traccar
--     positions by the trip builder job; playback stays raw in tc_positions)
-- ===========================================================================
CREATE TABLE trips (
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vehicle_id     integer NOT NULL REFERENCES vehicles(id),
    driver_id      integer REFERENCES drivers(id),
    start_time     timestamptz NOT NULL,
    end_time       timestamptz,
    start_lat      double precision,
    start_lng      double precision,
    end_lat        double precision,
    end_lng        double precision,
    start_location text,
    end_location   text,
    start_odometer numeric,
    end_odometer   numeric,
    distance_km    numeric,
    max_speed      numeric,
    average_speed  numeric,
    moving_sec     integer,
    idle_sec       integer,
    stop_sec       integer,
    inactive_sec   integer,
    trip_status    text NOT NULL DEFAULT 'Unclassified',
    alerts         integer DEFAULT 0
);
CREATE INDEX ON trips (vehicle_id, start_time DESC);

CREATE TABLE driver_scoring (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    driver_id   integer NOT NULL REFERENCES drivers(id),
    period_from date NOT NULL,
    period_to   date NOT NULL,
    score       numeric,
    details     jsonb,
    UNIQUE (driver_id, period_from, period_to)
);

-- ===========================================================================
-- 5. ALERTING & COMMS
-- ===========================================================================
CREATE TABLE alert_rules (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     integer REFERENCES users(id),
    name        text NOT NULL,
    alert_type  text NOT NULL,        -- speeding | geofence | sos | idle | ...
    scope       jsonb,                -- vehicles/groups the rule applies to
    threshold   jsonb,                -- typed per alert_type
    severity    text NOT NULL DEFAULT 'info',
    channels    text[] NOT NULL DEFAULT '{push}',   -- push|email|sms|whatsapp
    enabled     boolean NOT NULL DEFAULT true,
    created_at  timestamptz NOT NULL DEFAULT now(),
    modified_at timestamptz
);

CREATE TABLE notifications (
    id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id          integer REFERENCES users(id),
    vehicle_id       integer REFERENCES vehicles(id),
    tc_event_id      bigint,          -- provenance link to tc_events.id (no FK)
    kind             text NOT NULL,
    severity         text NOT NULL DEFAULT 'info',
    status           text,
    title            text,
    message          text,
    location_address text,
    driver_name      text,
    driver_contact   text,
    at               timestamptz NOT NULL DEFAULT now(),
    is_read          boolean NOT NULL DEFAULT false,
    cleared_at       timestamptz,
    email_sent       boolean DEFAULT false,
    sms_sent         boolean DEFAULT false,
    whatsapp_sent    boolean DEFAULT false
);
CREATE INDEX ON notifications (user_id, at DESC);
CREATE INDEX ON notifications (user_id, is_read) WHERE NOT is_read;

CREATE TABLE notification_settings (
    id       integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id  integer NOT NULL UNIQUE REFERENCES users(id),
    settings jsonb NOT NULL DEFAULT '{}'
);

CREATE TABLE push_tokens (
    id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    integer NOT NULL REFERENCES users(id),
    token      text NOT NULL UNIQUE,
    platform   text,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE email_outbox (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    to_email   text NOT NULL,
    subject    text,
    body       text,
    status     text NOT NULL DEFAULT 'queued',   -- queued|sent|failed
    created_at timestamptz NOT NULL DEFAULT now(),
    sent_at    timestamptz
);
CREATE INDEX ON email_outbox (status) WHERE status = 'queued';

CREATE TABLE sms_outbox (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    to_number  text NOT NULL,
    body       text,
    status     text NOT NULL DEFAULT 'queued',
    created_at timestamptz NOT NULL DEFAULT now(),
    sent_at    timestamptz
);
CREATE INDEX ON sms_outbox (status) WHERE status = 'queued';

CREATE TABLE conversations (
    id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id integer REFERENCES companies(id),
    subject    text,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE messages (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id integer NOT NULL REFERENCES conversations(id),
    sender_user_id  integer REFERENCES users(id),
    body            text NOT NULL,
    at              timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE sos_acknowledgements (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tc_event_id  bigint NOT NULL,       -- the sos row in tc_events
    vehicle_id   integer REFERENCES vehicles(id),
    acked_by     integer REFERENCES users(id),
    acked_at     timestamptz,
    resolution   text
);

-- ===========================================================================
-- 6. OPERATIONS / REPORTS / WASL
-- ===========================================================================
CREATE TABLE maintenance_reminders (
    id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id      integer REFERENCES companies(id),
    vehicle_id      integer NOT NULL REFERENCES vehicles(id),
    user_id         integer REFERENCES users(id),
    kind            text NOT NULL,          -- oil | tires | inspection | ...
    title           text,
    status          text NOT NULL DEFAULT 'upcoming',
    due_date        timestamptz,
    due_odometer_km numeric,
    created_at      timestamptz NOT NULL DEFAULT now(),
    modified_at     timestamptz
);

CREATE TABLE notes (
    id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vehicle_id integer REFERENCES vehicles(id),
    user_id    integer REFERENCES users(id),
    body       text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE report_favorites (
    id      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id integer NOT NULL REFERENCES users(id),
    report  text NOT NULL,
    params  jsonb
);

CREATE TABLE saved_reports (
    id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    integer NOT NULL REFERENCES users(id),
    name       text NOT NULL,
    report     text NOT NULL,
    params     jsonb,               -- includes the report range
    snapshot   jsonb,               -- frozen result rows at save time
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE scheduled_reports (
    id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    integer NOT NULL REFERENCES users(id),
    name       text NOT NULL,
    report     text NOT NULL,
    params     jsonb,
    cron       text NOT NULL,           -- schedule expression
    recipients text[],
    enabled    boolean NOT NULL DEFAULT true
);

CREATE TABLE scheduled_report_runs (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scheduled_report_id integer NOT NULL REFERENCES scheduled_reports(id),
    ran_at              timestamptz NOT NULL DEFAULT now(),
    status              text,
    output_url          text
);

CREATE TABLE shared_reports (
    id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    integer REFERENCES users(id),
    token      text UNIQUE NOT NULL,
    report     text NOT NULL,
    params     jsonb,
    expires_at timestamptz
);

CREATE TABLE saved_filters (
    id      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id integer NOT NULL REFERENCES users(id),
    scope   text,
    filter  jsonb
);

CREATE TABLE report_settings (
    id      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id integer NOT NULL UNIQUE REFERENCES users(id),
    settings jsonb NOT NULL DEFAULT '{}'
);

CREATE TABLE wasl_companies (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id  integer REFERENCES companies(id),
    wasl_ref    text,
    status      text,
    payload     jsonb,
    updated_at  timestamptz
);

CREATE TABLE wasl_vehicles (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vehicle_id  integer REFERENCES vehicles(id),
    wasl_ref    text,
    status      text,
    payload     jsonb,
    updated_at  timestamptz
);

CREATE TABLE wasl_drivers (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    driver_id   integer REFERENCES drivers(id),
    wasl_ref    text,
    status      text,
    payload     jsonb,
    updated_at  timestamptz
);

CREATE TABLE wasl_status (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity     text NOT NULL,           -- company|vehicle|driver
    entity_id  integer NOT NULL,
    status     text NOT NULL,
    detail     jsonb,
    at         timestamptz NOT NULL DEFAULT now()
);

-- ===========================================================================
-- 7. TRACCAR-BACKED VIEWS & FUNCTIONS (single source of truth: tc_*)
--    Traccar attributes JSON may contain  escapes → always strip.
-- ===========================================================================

-- 7.1 Live snapshot per vehicle — feeds LiveTrackingPayloadDto / map screen.
--     30-day fixtime fence keeps chunk pruning effective; a vehicle silent
--     longer shows NULL live fields (it is offline anyway).
CREATE OR REPLACE VIEW v_live_vehicles AS
SELECT
    v.id                AS vehicle_id,
    v.vehicle_name,
    v.plate_number,
    v.imei,
    d.id                AS tc_device_id,
    d.status            AS traccar_status,        -- online|offline|unknown
    d.lastupdate AT TIME ZONE 'UTC'      AS last_update,
    p.fixtime    AT TIME ZONE 'UTC'      AS position_time,
    p.latitude          AS lat,
    p.longitude         AS lng,
    round((p.speed * 1.852)::numeric, 1) AS speed_kmh,   -- knots → km/h
    p.course            AS heading,
    p.address,
    a.attrs ->> 'ignition'                    AS ignition,
    a.attrs ->> 'motion'                      AS motion,
    (a.attrs ->> 'fuel')::numeric             AS fuel_level,
    (a.attrs ->> 'sat')::int                  AS satellites,
    (a.attrs ->> 'rssi')::int                 AS gsm_signal,
    (a.attrs ->> 'power')::numeric            AS battery_external_v,
    (a.attrs ->> 'batteryLevel')::numeric     AS battery_internal_percent,
    (a.attrs ->> 'odometer')::numeric / 1000  AS odometer_km,
    a.attrs                                   AS raw_attributes
FROM telematics.vehicles v
JOIN tc_devices d ON d.uniqueid = v.imei
LEFT JOIN LATERAL (
    SELECT * FROM tc_positions p
    WHERE p.deviceid = d.id
      AND p.fixtime > (now() - interval '30 days')::timestamp
    ORDER BY p.fixtime DESC
    LIMIT 1
) p ON true
LEFT JOIN LATERAL (
    SELECT replace(p.attributes, '\u0000', '')::jsonb AS attrs OFFSET 0
) a ON p.id IS NOT NULL
WHERE v.deleted_at IS NULL;

-- 7.2 Playback / tracking-console route (TrackingRoutePoint[]).
CREATE OR REPLACE FUNCTION fn_playback(
    p_vehicle_id integer,
    p_from       timestamptz,
    p_to         timestamptz)
RETURNS TABLE (
    ts          timestamptz,
    lat         double precision,
    lng         double precision,
    speed_kmh   numeric,
    heading     double precision,
    ignition    text,
    fuel        numeric,
    temperature numeric
)
LANGUAGE sql STABLE AS $$
    SELECT
        p.fixtime AT TIME ZONE 'UTC',
        p.latitude,
        p.longitude,
        round((p.speed * 1.852)::numeric, 1),
        p.course,
        a.attrs ->> 'ignition',
        (a.attrs ->> 'fuel')::numeric,
        (a.attrs ->> 'temp1')::numeric
    FROM telematics.vehicles v
    JOIN tc_devices d ON d.uniqueid = v.imei
    JOIN tc_positions p ON p.deviceid = d.id
    CROSS JOIN LATERAL (
        SELECT replace(p.attributes, '\u0000', '')::jsonb AS attrs OFFSET 0
    ) a
    WHERE v.id = p_vehicle_id
      AND p.fixtime >= (p_from AT TIME ZONE 'UTC')::timestamp
      AND p.fixtime <  (p_to   AT TIME ZONE 'UTC')::timestamp
    ORDER BY p.fixtime
$$;

-- 7.3 Event feed (notifications source / harsh & sos views).
CREATE OR REPLACE VIEW v_vehicle_events AS
SELECT
    e.id          AS tc_event_id,
    v.id          AS vehicle_id,
    v.company_id,
    e.type,
    e.eventtime AT TIME ZONE 'UTC' AS at,
    e.positionid,
    e.attributes
FROM tc_events e
JOIN tc_devices d ON d.id = e.deviceid
JOIN telematics.vehicles v ON v.imei = d.uniqueid;

CREATE OR REPLACE VIEW v_harsh_events AS
SELECT * FROM v_vehicle_events
WHERE type = 'alarm'
  AND attributes ~ '(hardBraking|hardAcceleration|hardCornering)';

CREATE OR REPLACE VIEW v_sos_events AS
SELECT ev.*, ack.acked_by, ack.acked_at, ack.resolution
FROM v_vehicle_events ev
LEFT JOIN telematics.sos_acknowledgements ack ON ack.tc_event_id = ev.tc_event_id
WHERE ev.type = 'alarm' AND ev.attributes ~ '"alarm"\s*:\s*"sos"';

-- 7.4 Daily activity per vehicle from the rollup layer (dashboards/KPIs) —
--     answers in milliseconds, no hypertable scan.
CREATE OR REPLACE VIEW v_vehicle_daily_stats AS
SELECT
    v.id  AS vehicle_id,
    v.company_id,
    s.day,
    s.msg_count,
    s.moving_msgs,
    s.stopped_msgs,
    s.idle_msgs,
    s.first_fixtime AT TIME ZONE 'UTC' AS first_message,
    s.last_fixtime  AT TIME ZONE 'UTC' AS last_message,
    round((s.interval_sum        / NULLIF(s.interval_cnt, 0))::numeric, 1)        AS avg_interval_sec,
    round((s.moving_interval_sum / NULLIF(s.moving_interval_cnt, 0))::numeric, 1) AS moving_avg_interval_sec
FROM device_daily_stats s
JOIN tc_devices d ON d.id = s.deviceid
JOIN telematics.vehicles v ON v.imei = d.uniqueid;

COMMIT;

-- ============================================================================
-- DEPLOY NOTES (not executed):
-- 1. ALTER ROLE telematics PASSWORD '...' at deploy; add pg_hba line for the
--    Fleet VM IP; add a [databases] pool entry in pgbouncer.ini.
-- 2. Populate vehicles.tc_device_id after import:
--      UPDATE telematics.vehicles v SET tc_device_id = d.id
--      FROM tc_devices d WHERE d.uniqueid = v.imei;
-- 3. dashboard-kpis / dashboard-*-summary / vehicleDetails collections are
--    NOT tables: they are computed from v_vehicle_daily_stats + trips +
--    notifications at request time (or a small matview if needed later).
-- 4. Trip building: schedule a job that segments tc_positions into
--    telematics.trips using ignition/motion (rollup-style, per closed day).
-- 5. notifications.tc_event_id + sos_acknowledgements.tc_event_id are plain
--    bigints on purpose — tc_events rows expire via 12-month retention.
-- ============================================================================
